server:
  port: 8083
  url: "https://dev-apim.virtus-way.org/gateway/"
spring:
  application:
    name: tracker
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    dispatch-options-request: true
  jmx:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob: 
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://dev-way-db.cecmaagdmtj5.us-east-2.rds.amazonaws.com:5432/virtus_way?currentSchema=tracker
    username: virtus
    password: Virtu$w4y
    dbcp2:
      initial-size: 5
      max-total: 40
      pool-prepared-statements: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: tracker
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    username: virtus-way@outlook.com
    password: 'Virtu$w4y'
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true
          ssl: 
            trust: smtp.office365.com
        transport: 
          protocol: smt
jwt:
  config:
    type: encrypted
wso2:
    core-api-key: "eyJ4NXQiOiJOVGRtWmpNNFpEazNOalkwWXpjNU1tWm1PRGd3TVRFM01XWXdOREU1TVdSbFpEZzROemM0WkE9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ2aXJ0dXNAY2FyYm9uLnN1cGVyIiwiYXBwbGljYXRpb24iOnsib3duZXIiOiJ2aXJ0dXMiLCJ0aWVyUXVvdGFUeXBlIjpudWxsLCJ0aWVyIjoiVW5saW1pdGVkIiwibmFtZSI6IkNvcmUtQXBwbGljYXRpb24iLCJpZCI6MiwidXVpZCI6ImI5MjNiM2E0LTYzNDktNDQzOS04ODFlLWNkNzJkODQ3ZGE5ZCJ9LCJpc3MiOiJodHRwczpcL1wvZGV2LWFwaW0udmlydHVzLXdheS5vcmc6NDQzXC9vYXV0aDJcL3Rva2VuIiwidGllckluZm8iOnsiVW5saW1pdGVkIjp7InRpZXJRdW90YVR5cGUiOiJyZXF1ZXN0Q291bnQiLCJncmFwaFFMTWF4Q29tcGxleGl0eSI6MCwiZ3JhcGhRTE1heERlcHRoIjowLCJzdG9wT25RdW90YVJlYWNoIjp0cnVlLCJzcGlrZUFycmVzdExpbWl0IjowLCJzcGlrZUFycmVzdFVuaXQiOm51bGx9fSwia2V5dHlwZSI6IlBST0RVQ1RJT04iLCJwZXJtaXR0ZWRSZWZlcmVyIjoiIiwic3Vic2NyaWJlZEFQSXMiOlt7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoid2F5LWNvcmUiLCJjb250ZXh0IjoiXC9jb3JlXC92MSIsInB1Ymxpc2hlciI6InZpcnR1cyIsInZlcnNpb24iOiJ2MSIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifSx7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoid2F5LWJ1c2luZXNzIiwiY29udGV4dCI6IlwvYnVzaW5lc3NcL3YxIiwicHVibGlzaGVyIjoidmlydHVzIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9LHsic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktdHJhY2tlciIsImNvbnRleHQiOiJcL3RyYWNrZXJcL3YxIiwicHVibGlzaGVyIjoidmlydHVzIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9XSwicGVybWl0dGVkSVAiOiIiLCJpYXQiOjE2MzUxODY0NjYsImp0aSI6ImNhNzU1NzU5LWFjOTEtNDg0NC05OWQ0LTU5ZDAyM2JmNzVmNCJ9.iXB_ktH0xw_j02DjaOoL8ODw3XS9jdg0_YkgV9w3s-8LxI_Bd2ElJGps1yK2S8Mx58O_LTCLqWcKR8x1O0n_0dnjJZjpqQ_WJi6KIS-0xgJL4YKsqeeZdwuTk-yfh9fEX3CrSeI0HGejvvx-vQLdgRnXQBQ7RGdXVEi_HU7SPGYtd1oQIabbEH_V7ZbicWNmj1fZXTj3H7nlPXc0xIjoJiEO6AkSiVkcXw_ftD9i7c5gN9sRquWuPUAbV5mekkVoCdjzwQQhyTSrS04ewQI8LIlaJZrs23_dTefNTxgPgpuJD8-g0unMi0dXz6QpXvemyh2zCHewSlJcrqqKfLXrUw=="
