server:
  port: 8082
  url: "http://localhost:8280/"
spring:
  application:
    name: business
  jackson:
    default-property-inclusion: NON_NULL
  mvc:
    dispatch-options-request: true
  jmx:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob: 
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/virtus_way?currentSchema=business
    username: virtus
    password: master
    dbcp2:
      initial-size: 5
      max-total: 40
      pool-prepared-statements: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: business
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    username: virtus-way@outlook.com
    password: 'Virtu$w4y'
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail: 
        smtp: 
          auth: true
          starttls:
            enable: true
          ssl: 
            trust: smtp.office365.com
        transport: 
          protocol: smt
jwt:
  config:
    type: encrypted
wso2:
    core-api-key: "eyJ4NXQiOiJOVGcyTUdReFpXRmtZVE13WmpNMVlUSmtZbUppWlRSaU4yRmhZamt6WkRoaU5UQTJZMk5sWmc9PSIsImtpZCI6ImdhdGV3YXlfY2VydGlmaWNhdGVfYWxpYXMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbkBjYXJib24uc3VwZXIiLCJhcHBsaWNhdGlvbiI6eyJvd25lciI6ImFkbWluIiwidGllclF1b3RhVHlwZSI6bnVsbCwidGllciI6IlVubGltaXRlZCIsIm5hbWUiOiJDb3JlLUFwcGxpY2F0aW9uIiwiaWQiOjUsInV1aWQiOiIyNzUyZDk3Yi1hYmZkLTQwNjUtODFlMy01NGIyODFiZGYzMzYifSwiaXNzIjoiaHR0cHM6XC9cL3dzbzIudmlydHVzLnVmY2cuZWR1LmJyOjk0NDNcL29hdXRoMlwvdG9rZW4iLCJ0aWVySW5mbyI6eyJVbmxpbWl0ZWQiOnsidGllclF1b3RhVHlwZSI6InJlcXVlc3RDb3VudCIsImdyYXBoUUxNYXhDb21wbGV4aXR5IjowLCJncmFwaFFMTWF4RGVwdGgiOjAsInN0b3BPblF1b3RhUmVhY2giOnRydWUsInNwaWtlQXJyZXN0TGltaXQiOjAsInNwaWtlQXJyZXN0VW5pdCI6bnVsbH19LCJrZXl0eXBlIjoiUFJPRFVDVElPTiIsInBlcm1pdHRlZFJlZmVyZXIiOiIiLCJzdWJzY3JpYmVkQVBJcyI6W3sic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktYnVzaW5lc3MiLCJjb250ZXh0IjoiXC9idXNpbmVzc1wvdjEiLCJwdWJsaXNoZXIiOiJhZG1pbiIsInZlcnNpb24iOiJ2MSIsInN1YnNjcmlwdGlvblRpZXIiOiJVbmxpbWl0ZWQifSx7InN1YnNjcmliZXJUZW5hbnREb21haW4iOiJjYXJib24uc3VwZXIiLCJuYW1lIjoid2F5LXRyYWNrZXIiLCJjb250ZXh0IjoiXC90cmFja2VyXC92MSIsInB1Ymxpc2hlciI6ImFkbWluIiwidmVyc2lvbiI6InYxIiwic3Vic2NyaXB0aW9uVGllciI6IlVubGltaXRlZCJ9LHsic3Vic2NyaWJlclRlbmFudERvbWFpbiI6ImNhcmJvbi5zdXBlciIsIm5hbWUiOiJ3YXktY29yZSIsImNvbnRleHQiOiJcL2NvcmVcL3YxIiwicHVibGlzaGVyIjoiYWRtaW4iLCJ2ZXJzaW9uIjoidjEiLCJzdWJzY3JpcHRpb25UaWVyIjoiVW5saW1pdGVkIn1dLCJwZXJtaXR0ZWRJUCI6IiIsImlhdCI6MTYzMzcxNzMxMywianRpIjoiNzM4NzUxZjktOTc5Mi00MWE2LWEzYzEtMWZmM2M0ZTNiYzU3In0=.viLaNZJz-7lJ5fPFz7zz7_bs6IZzXGyQ2BK4ZNTIAQGOcppGlqaaFGp22GyZV0DHdKR0wgZVDPoskPSMavlnhPzKG66o58tYMjPJcTMigiv69E7J_daWkpDgtctPNiVUsgRgvEJUT5lgZeNZ2mZMvQCdM2xui4uFAUX6Xo9RJYW0X5UUDpsdpr6rbC_xtLzoJkDLK41H7fkjY39fQ9SkLhoeOfm4Ivb9LDIrPYVlDYAGadjlir9F9IFCrjGDF4iVSKzA1J8vLJ9eWO2Bi71Tpur1lBYk_atTC8P2_TREqJ3TjZzSAW0BOw-1nCJdGS0MccwrfRigJeIYngFvaou-9A=="

